version: "3.9"
services:
  db:
    image: postgres
    container_name: pg-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=database
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - network
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/var/lib/redis/data
  kafka:
    image: apache/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - network
  web:
    build: ./services/client
    container_name: web
    ports:
      - 3000:3000
    volumes:
      - ./services/client:/usr/src/web
    command:
      - pnpm i
      - pnpm run build
      - pnpm run start
    depends_on:
      - api
    networks:
      - network
  admin:
    build: ./services/admin
    container_name: admin
    ports:
      - 8000:8000
    volumes:
      - ./services/admin:/usr/src/admin
    command:
      - pnpm i
      - pnpm run build
      - pnpm run start
    depends_on:
      - db
      - redis
      - kafka
    networks:
      - network
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - admin
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - network
networks:
  network:
